### ISSUE TITLE
configure-cpu-set.sh should be called multiple times

### ISSUE THREAD

**Issue by hgn** [hgn/linux-sched-deadline-analyzer#3]
Currently if called multiple times, the script failes with "directory already available". This can be done
in two ways:

- cleanup everything in configure-cpu-set.sh  before setting the directory structure (better)
- or simple check that the dir is already available, if so, don't create a new one.

Solution is probably the more future proof.

**Comment by dasteihn** [comment]
As far as I understood the Kernel VFS magic, you can not remove some elements of the CPU-set, even as root, until the machine is restarted.
Therefore the second option appears to be more desirable

**Comment by hgn** [comment]
Ok, then this way! I pushed some changes now - it works everything in my setup for now

**Comment by dasteihn** [comment]
Maybe we can view this as solved now. Or should we strive for something more elegant?
